### ISSUE TITLE
Hello i need ur help!

### ISSUE THREAD

**Issue by yan4ikyt** [Nisto/ps2-bankmod#2]
I am found on one game Bank Sound files. But this game on psp. I viewed file via hex editor and it's different from ps2 bank sound file (HD file is diffrent). Can u help me, please.

**Comment by Nisto** [comment]
@yan4ikyt Unfortunately, I don't have much knowledge about PSP, nor its HD format. Since you say it's different from the PS2 format, this also sounds like an irrelevant issue for this repository. If you believe there's a negligible difference between the formats, you can try contacting me via a DM somewhere, and I might be able to put something together, but for now I am closing this issue.
